name: A-M Rantanen
favicon: null
layout_spectrum: 0.6661891031544656
typography_spectrum: 0.35667978576384485
title: A-M Rantanen - Photography and stuff
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060807'
    - '#136500'
    - '#d7fdfe'
    - '#339b2f'
    - '#5c98bd'
  brandStrength: 1
  lightness: 0.6175184748135507
  saturation: 0.6732936722692102
  rhythmicContrast: 0.3867966958787292
purpose: []
