name: A-M Rantanen
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: A-M Rantanen - Photography and stuff
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060807'
    - '#136500'
    - '#d7fdfe'
    - '#339b2f'
    - '#5c98bd'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
